[package]
name = "three0_storage"
version = "0.1.0"
authors = ["Uneeb Sajjad <usajjad5@utexas.edu>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
serde_json = "1.0"